server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Enable gzip compression for manifest.json and catalog.json
    gzip on;
    gzip_types application/json text/html text/css application/javascript;
    gzip_min_length 1000;
}
