services:
  namenode:
    image: apache/hadoop:3.5.0
    hostname: namenode
    user: root
    command: ["hdfs", "namenode"]
    ports:
      - "${NAMENODE_UI_PORT:-9870}:9870"
    environment:
      CORE-SITE.XML_fs.defaultFS: hdfs://namenode:9000
      HDFS-SITE.XML_dfs.replication: "1"
      HDFS-SITE.XML_dfs.permissions.enabled: "false"
      HDFS-SITE.XML_dfs.namenode.rpc-bind-host: "0.0.0.0"
      HDFS-SITE.XML_dfs.namenode.http-bind-host: "0.0.0.0"
      HDFS-SITE.XML_dfs.namenode.name.dir: file:///opt/hadoop/data/nameNode
      HDFS-SITE.XML_dfs.client.use.datanode.hostname: "true"
      HDFS-SITE.XML_dfs.datanode.use.datanode.hostname: "true"
      ENSURE_NAMENODE_DIR: /opt/hadoop/data/nameNode/current
    volumes:
      - hadoop_namenode:/opt/hadoop/data/nameNode
    networks:
      - ktdl-network

  datanode:
    image: apache/hadoop:3.5.0
    hostname: datanode
    user: root
    command: ["hdfs", "datanode"]
    depends_on:
      - namenode
    environment:
      CORE-SITE.XML_fs.defaultFS: hdfs://namenode:9000
      HDFS-SITE.XML_dfs.replication: "1"
      HDFS-SITE.XML_dfs.permissions.enabled: "false"
      HDFS-SITE.XML_dfs.datanode.address: "0.0.0.0:9866"
      HDFS-SITE.XML_dfs.datanode.http.address: "0.0.0.0:9864"
      HDFS-SITE.XML_dfs.datanode.data.dir: file:///opt/hadoop/data/dataNode
      HDFS-SITE.XML_dfs.client.use.datanode.hostname: "true"
      HDFS-SITE.XML_dfs.datanode.use.datanode.hostname: "true"
    volumes:
      - hadoop_datanode:/opt/hadoop/data/dataNode
    networks:
      - ktdl-network

volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  ktdl-network:
    external: true
